ignore:
  - "modules/tui"
  - "modules/gui"
  - "src/main/scala/HearthstoneMini.scala"
  - "modules/core/src/main/scala/core/controller/module"
  - "modules/persistence/src/main/scala/PersistenceRestApi.scala"
  - "modules/core/src/main/scala/core/controller/service/HttpService.scala"
  - "modules/core/src/main/scala/CoreRunner.scala"
  - "modules/persistence/src/main/scala/PersistenceModule.scala"
  - "modules/persistence/src/main/scala/database/DaoInterface.scala"
  - "modules/core/src/main/scala/core/controller/component/ControllerServiceInterface.scala"
