ignore:
  - "modules/tui"
  - "modules/gui"
  - "src/main/scala/HearthstoneMini.scala"
  - "modules/core/src/main/scala/core/controller/module"
  - "modules/persistence/src/main/scala/PersistenceRestApi.scala"