services:
  gui:
    image: gui:1.1.0
    depends_on:
      - core
      - persistence
    environment:
      - DISPLAY=host.docker.internal:0
    network_mode: "host"

  tui:
    image: tui:1.1.0
    network_mode: "host"
    stdin_open: true
    tty: true
    depends_on:
      - core
      - persistence

  persistence:
    image: persistence:1.1.0
    ports: 
      - "9021:9021"
    network_mode: "host"
    depends_on:
      - postgres_db

  core:
    image: core:1.1.0
    ports: 
      - "9031:9031"
    depends_on:
      - persistence
    network_mode: "host"

  postgres_db:
    image: postgres
    restart: always
    container_name: postgres_database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "9051:5432"
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "9061:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

networks:
  my_network:
