services:
  gui:
    image: gui:1.1.0
    depends_on:
      - core
      - persistence
    environment:
      - DISPLAY=host.docker.internal:0
    network_mode: "host"

  tui:
    image: tui:1.1.0
    network_mode: "host"
    stdin_open: true
    tty: true
    depends_on:
      - core
      - persistence

  persistence:
    image: persistence:1.1.0
    ports: 
      - "9021:9021"
    network_mode: "host"

  core:
    image: core:1.1.0
    ports: 
      - "9031:9031"
    depends_on:
      - persistence
    network_mode: "host"
